### ISSUE TITLE
Licensing declaration absent

### ISSUE THREAD

**Issue by jengelh** [gap-packages/crypting#6]
I cannot find a proper license declaration to this package. That makes it impossible to package for Linux distros. crypting is new in GAP 4.9.2 and therefore somehow blocks updating from 4.8.

**Comment by fingolfin** [comment]
First off, I support the notation that crypting should declare an explicit license wholeheartedly.

However, I have to also say this:

> That makes it impossible to package for Linux distros.

This is factually incorrect. It does, however, make it impossible to package for distributions (anywhere, this has nothing to do with Linux) that pay close attention to licensing and that insist on authors providing an explicit license, i.e., where the implicit license granted by distributing the package on GitHub is not deemed enough. Which is fair, but please don't pretend this affects all distros, or that it has anything to do with Linux.
